### ISSUE TITLE
Dropdowns in mobile do not work

### ISSUE THREAD

**Issue by flexnds** [bootflat/bootflat.github.io#91]
The dropdowns in mobile do not work. This is apparent even on your demo/documentation page here: http://bootflat.github.io/documentation.html

**Comment by Chachaproper** [comment]
A partial solution to the problem:
```css
.selecter {
   cursor: pointer;
}

.selecter .selecter-options {
   cursor: pointer;
}
```
